name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  DB_URL: ${{secrets.DB_URL}}
  DB_TEST_URL: ${{secrets.DB_TEST_URL}}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install and Test client
        working-directory: ./client
        run: | 
          npm install
          npm run test
        
      - name: Install and Test server
        working-directory: ./server
        run: | 
          npm install
          export DB_URL=$DB_URL
          export DB_TEST_URL=$DB_TEST_URL
          npm run test

      - name: Build Client Docker Image
        working-directory: ./client
        run: | 
          docker build -t ritwikkapoor/mern-anon-notes:client-${{github.run_number}} -t ritwikkapoor/mern-anon-notes:client-latest .
        
      - name: Build Server Docker Image
        working-directory: ./server
        run: | 
          docker build -t ritwikkapoor/mern-anon-notes:server-${{github.run_number}} -t ritwikkapoor/mern-anon-notes:server-latest .

      - name: Build Nginx Docker Image
        working-directory: ./nginx
        run: | 
          docker build -t ritwikkapoor/mern-anon-notes:nginx-${{github.run_number}} -t ritwikkapoor/mern-anon-notes:nginx-latest .
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push images to Docker Hub
        run: |
          docker push ritwikkapoor/mern-anon-notes:client-${{github.run_number}} 
          docker push ritwikkapoor/mern-anon-notes:server-${{github.run_number}} 
          docker push ritwikkapoor/mern-anon-notes:nginx-${{github.run_number}} 
          docker push ritwikkapoor/mern-anon-notes:client-latest 
          docker push ritwikkapoor/mern-anon-notes:server-latest 
          docker push ritwikkapoor/mern-anon-notes:nginx-latest 

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.EB_APP_NAME }}
          environment_name: ${{ secrets.EB_ENV_NAME }}
          region: us-east-1
          version_label: "version-${{ github.run_number }}"
          deployment_package: docker-compose.yml
        

 